apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-tut-deployment
  labels:
    app: docker-tut
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-tut
  template:
    metadata:
      labels:
        app: docker-tut
    spec:
      containers:
        - name: docker-tut
          image: app-tut:v1.3
          imagePullPolicy: Never
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
          ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: docker-tut-service
spec:
  type: NodePort
  selector:
    app: docker-tut
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-tut-deployment
  labels:
    app: redis-tut
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-tut
  template:
    metadata:
      labels:
        app: redis-tut
    spec:
      containers:
        - name: redis-tut
          image: redis:6.0-alpine
          imagePullPolicy: Always
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-tut-service
spec:
  type: ClusterIP
  selector:
    app: redis-tut
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
